version: '2'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest 
    restart: "always"
    ports:
      - "80:80"
      - "443:443"
  jenkins:
    build: ./jenkins
    ports:
      - "8080:8080"
  artifactory:
    image: jfrog-docker-reg2.bintray.io/jfrog/artifactory-registry:latest
    ports:
      - "8081:8081"
  vault:
    build: ./vault
    command: server -config=/config/dev.hcl
    ports:
      - "8200:8200"

