version: '2'
services:
  minitwit:
    build: ./minitwit
    ports:
      - "5000:5000"
    depends_on:
      - db
      - vault
    environment:
      - "constraint:environment==frontend"
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=toto
    command: postgres
  vault_init:
    build: ./vault_initializer
    env_file: ./vault_initializer/dev.env
    depends_on:
      - db
      - minitwit
      - vault
  vault:
    build: ./vault
    command: server -config=/config/dev.hcl
