version: '2'
services:
  minitwit:
    build: ./minitwit
    ports:
      - "5000:5000"
    depends_on:
      - vault
      - db
  vault: 
    build: ./vault
    command: server -config=/config/dev.hcl
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=toto
    command: postgres
    ports:
      - "5432:5432"
