version: '2'
services:
  minitwit:
    build: ./minitwit
    ports:
      - "5000:5000"
    depends_on:
      - vault
  vault: 
    build: ./vault
    ports:
      - "8200:8200"
    command: server -config=/config/dev.hcl
